name: Build
on:
  schedule:
    - cron: '21 */2 * * *'
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test_build:
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: "Place wintun.dll"
        run: cp deps/wintun/bin/amd64/wintun.dll ./
      - name: build
        uses: goreleaser/goreleaser-action@v5
        env:
          BUILD_ENV: "development"
        with:
          version: latest
          args: build --clean --snapshot --verbose
      - name: Upload flyctl for preflight
        uses: actions/upload-artifact@v4
        with:
          name: flyctl
          path: dist/default_linux_amd64_v1/flyctl
          overwrite: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deployer docker build
        run: |
          mkdir -p bin
          cp dist/default_linux_amd64_v1/flyctl bin/flyctl
          chmod +x bin/flyctl
          docker build -t flyio/deployer:${{ github.sha }} -f deployer.Dockerfile .
          docker push flyio/deployer:${{ github.sha }}

  preflight:
    needs: test_build
    uses: ./.github/workflows/preflight.yml
    secrets: inherit
